import "./test/base64.test.ts";
import "./test/crypto.test.ts";
import "./test/date.test.ts";
import "./test/deflate.test.ts";
import "./test/fetch.test.ts";
import "./test/minipack.test.ts";
import "./test/path.deno.test.ts";
import "./test/platform.deno.test.ts";
import "./test/text.test.ts";